### PR TITLE
automatic blocked dates

### PR DESCRIPTION
**Pull request by p3rc1us**
fix for issue #130

### CODE REVIEW

**Review by cimafrancamae — APPROVED** [review]

**Comment by cimafrancamae** [comment]
For future commit, user shouldn't be able to unblock past dates

**Comment by p3rc1us** [comment]
thanks. here it is, pr #148  @cimafrancamae

**Comment by cimafrancamae** [comment]
There's an issue pala to this. Kindly refer to Ty's comment here https://github.com/TyJacalan/booking-app/issues/130#issuecomment-2158043620 @p3rc1us

**Comment by cimafrancamae** [comment]
@p3rc1us Not really sure why currently, the freelancer can block past dates and blocked dates can't be unblocked. Is that just a front-end issue? Kindly advise @TyJacalan

**Pull request closed without merging**
