### PR TITLE
Feat/paymongo

### PR DESCRIPTION
**Pull request by TyJacalan**
:warning: Large pull request :warning: 

## Requirements
1. Install Faraday Gem
```
bundle
```
2. connect the payment_controller
```
bin/rails assets:clobber # only if the controller doesn't connect
bin/rails assets:precompile
```

## Demo
demo_paymongo

#### Add Faraday Gem
Full [documentation](https://github.com/lostisland/faraday). This gem is used to connect the Paymongo API.

#### Fix form builder
Form builder would throw errors in cases when `render_form_with` was used. In other words, if the form was created without an associated model. Since the form to trigger the paymongo payment does not require a model, I modified to form builder to function even if `@object` was not passed.

#### Integrate Paymongo Api
See full [documentation](https://developers.paymongo.com/docs/card-integration-test-cases). The application uses the [Payment Intent Workflow](https://developers.paymongo.com/docs/pipm-workflow), where (1) a payment intent is created, (2) a payment method is created, and (3) the payment method is attached to the payment intent and the payment is processed.
- Endpoints added:
   - checkout sessions (unused)
   - payment intent
   - payment method
- Notes (for production):
   - the api usage is only in _test mode_. Business registration is required for non-test mode usage. 
   - a `return_url` is required. The return_url is the page that the user will be redirected to after the payment process is complete. The return url is hardcoded to the localhost in this [file](app/services/paymongo/payment_intents.rb). Add a `:HOST_URL` env variable in the future.
   - after successful payment, the user is redirected to a paymongo interface where they can accept, deny, or expire a payment. This is _required in test mode_. The redirect in the [payments controller](app/controllers/payments_controller.rb) should be removed when used outside of test mode.

#### Users can use paymongo to pay for appointments
 - On appointment creation, a payment intent is simultaneously created.
 - The user is redirected to the payments page
 - The user selects a payment method (note that current options are gcash, paymaya, and card, but this can be expanded in the future). The [payment controller](app/javascript/controllers/payment_controller.js) handles the visible fields based on the payment method selected.
 - The user submits a form that creates a payment method
 - Simultaneously, the payment method is attached to the intent and the payment is processed by Paymongo
 - The user is redirected to a Paymongo interface
 - The user is redirected to the appointments index page

### CODE REVIEW

**Review by p3rc1us — APPROVED** [review]

**Comment by cimafrancamae** [comment]
I did all the requirements but I'm still getting a Faraday::ConnectionFailed error

image

Here are what I tried:
```
pg_ctl restart
bin/rails db:reset
bin/rails db:migrate
bin/rails db:seed
bin/rails assets:clobber
bin/rails assets:precompile
bundle
```

**Review by cimafrancamae — APPROVED** [review]

**Comment by TyJacalan** [comment]
> I did all the requirements but I'm still getting a `Faraday::ConnectionFailed` error
> 
> image
> Here are what I tried:
> 
> ```
> pg_ctl restart
> bin/rails db:reset
> bin/rails db:migrate
> bin/rails db:seed
> bin/rails assets:clobber
> bin/rails assets:precompile
> bundle
> ```

It's not a db or assets issue. Have you tried restarting the server?

`bin/dev`

**Comment by cimafrancamae** [comment]
> > I did all the requirements but I'm still getting a `Faraday::ConnectionFailed` error
> > image
> > Here are what I tried:
> > ```
> > pg_ctl restart
> > bin/rails db:reset
> > bin/rails db:migrate
> > bin/rails db:seed
> > bin/rails assets:clobber
> > bin/rails assets:precompile
> > bundle
> > ```
> 
> The Faraday connection is not a db or assets issue. Have you tried restarting the server?
> 
> `bin/dev`

I tried both `bin/dev` and `bin/rails s`, same result

`Faraday::ConnectionFailed (Failed to open TCP connection to :80 (Connection refused - connect(2) for nil port 80)):`

Is there anything I need to configure locally?

**Review by shinichikudo000 — APPROVED** [review]

**Comment by TyJacalan** [comment]
You can try testing it again @cimafrancamae @p3rc1us

**Comment by cimafrancamae** [comment]
It's working! But I guess the problem is when you choose a date that's only one day ahead of current date. In the screen recording below, I tried the next day's date and it returned an error. Then I tried next month's date and it worked:


https://github.com/TyJacalan/booking-app/assets/65450522/5782b8aa-173c-4c61-ba27-bfbb1d66a66c

Maybe let's not allow users to choose a date which is only a day ahead of current date? @TyJacalan

**Comment by p3rc1us** [comment]
Yep, works for me. @TyJacalan @cimafrancamae

**Comment by TyJacalan** [comment]
@cimafrancamae, pushed a commit to change the minimum date from 1 to 3 days. 

Also adjusted the appointment mailer logic on creation: (1) moved the file under the appointments module `app/services/appointments/new_appointment_mail.rb` and (2) set it to trigger when the payment is processed @p3rc1us.

**Comment by p3rc1us** [comment]
works fine bro, thanks! @TyJacalan 

image

**Pull request merged**
